name: Update LinkedIn Experience

on:
  schedule:
    # Uruchamiaj raz w tygodniu (niedziela o 6:00 UTC)
    - cron: '0 6 * * 0'
  workflow_dispatch:
    # Możliwość ręcznego uruchomienia

jobs:
  update-experience:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install axios
      
    - name: Update LinkedIn experience
      run: node scripts/update-linkedin-experience.js
      env:
        # Dodaj klucze API gdy będziesz miał publiczny profil:
        # LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
        # LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
        NODE_ENV: production
        
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add src/data/experience.json
        git commit -m "🔄 Auto-update LinkedIn experience $(date +'%Y-%m-%d %H:%M')" || exit 0
        
    - name: Push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
